#!/bin/sh

# This script is based on the post-install script created by sdsddsd1.

chmod u+s    "$KISS_ROOT/usr/bin/sway"

cat <<EOF
*** IMPORTANT ***
Sway is build with suid bit (chmod u+s).
Your user has to be in the video group.

addgroup USERNAME video
addgroup USERNAME input
*** IMPORTANT ***
EOF
